name: CI

permissions:
  contents: read
  security-events: write
  packages: read

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
      GITHUB_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
      BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v5
        with:
          node-version: 24.3.0
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm prettier --check .
      - run: pnpm lint
      - run: pnpm check
      - run: pnpm build

  codeql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript

      - uses: github/codeql-action/autobuild@v3

      - uses: github/codeql-action/analyze@v3
